#!/bin/bash
######################################################################
####   ProkaBIC-seq: Call copy number variations for prokaryote
####   Aurthor: Linjie Wu
####   Date: 201904018
######################################################################

#### Set paths
SoftwareDir="/data1/XiLab/ljwu/ProkaBIC-seq-master"
Samtools="${SoftwareDir}/src/samtools-0.1.7a_getUnique-0.1.3/samtools"
BICNorm="${SoftwareDir}/src/BICseq2-norm_v0.2.6/BICseq2-norm.pl"
BICSeg="${SoftwareDir}/src/BICseq2-seg_v0.7.3/BICseq2-seg.pl"
GenerateConf="${SoftwareDir}/src/GenerateConf.py"
OriCorrect="${SoftwareDir}/src/OricCorrection.R"

#### Usage
usage(){
    echo -e "Program: ProkaBIC-seq (Call copy number variations for prokaryote.)"
    echo -e "Usage: ProkaBIC-seq [options]"
    echo -e "      -h  display help info."
    echo -e "      -i  bam file generate by BWA. (required)"
    echo -e "      -o  prefix of output file (Default ProkaBIC-seq_tmp)."
    echo -e "      -s  Location of origin of replications seperated by comma (required), one can get this information"
    echo -e "          from DoriC database http://tubic.org/doric/public/index.php/index."
    echo -e "      -r  fasta file of reference file. (required)"
    echo -e "      -m  Mode for ProkaBIC-seq either GR or CNV (Default GR)"
    echo -e "      -l  penalty for BIC-seq2 (required if choose mode NormAndSeg)"
    echo -e "      -b  length of bin. (Defaut 1000)"
    echo -e "      -p  subsample percentage for normalization. (Default 0.5)"
    echo -e "      -d  the tmp directory. (Default ${SoftwareDir}/tmp)"
    echo -e "example: ProkaBIC-seq -i input.bam -r reference.fa -s start_of_Oric_region,end_of_Oric_region"
exit 1
}
## No parameters
if [ $# == 0 ]
then
usage
fi

## Initialize variables to default values
OUT="ProkaBIC-seq_tmp"
tmp_dir="${SoftwareDir}/tmp"
BIN="1000"
REF=""
ORloc=""
BAMINPUT=""
LAMBDA=""
MODE="GR"
PROB='0.5'

### Check the parameters
while getopts :i:o:s:r:d:b:m:l:p:h FLAG; do
  case $FLAG in
    i)  
      BAMINPUT=$OPTARG
      ;;
    o) 
      OUT=$OPTARG
      ;;
    s)  
      ORloc=$OPTARG
      ;;
    r)  
      REF=$OPTARG  
      ;;
    d)  
      tmp_dir=$OPTARG
      ;;
    b)
      BIN=$OPTARG
      ;;
    m)
      MODE=$OPTARG
      ;;
    l)
      LAMBDA=$OPTARG
      ;;
    p)
      PROB=$OPTARG
      ;;
    h)  
      usage
      ;;
    \?) 
      usage
      ;;
  esac
done
shift $((OPTIND-1))  #This tells getopts to move on to the next argument.
echo -e "ProkaBIC-seq -i ${BAMINPUT} -o ${OUT} -m ${MODE} -s ${ORloc} -r ${REF} -l ${LAMBDA} -b ${BIN} -d ${tmp_dir}"

if [ ! -x "$tmp_out" ]; then
mkdir -p ${tmp_dir}
fi

###### Norm
## Extract unique mapping reads
${Samtools} view -U BWA,${tmp_dir}/chr,N,N ${BAMINPUT}
mv ${tmp_dir}/chr*.seq ${tmp_dir}/${OUT}.seq

## Generate config files
python ${GenerateConf} ${REF} ${tmp_dir} ${OUT}

## Bininig and normalization
${BICNorm} -p ${PROB} -b ${BIN} ${tmp_dir}/conf_1 ${tmp_dir}/${OUT}_norm.out

## Remove the influence of  replication origin
Rscript ${OriCorrect} ${tmp_dir}/${OUT}.norm.bin ${ORloc} ${tmp_dir} ${OUT}


##### Segements
if [ ${MODE} == 'CNV' ]; then
${BICSeg} --lambda ${LAMBDA} ${tmp_dir}/conf_2 ${tmp_dir}/${OUT}_seg.out
fi

rm ${tmp_dir}/chr*
rm ${tmp_dir}/conf*
rm ${tmp_dir}/*.seq
